version: '3'
services:
  spring:
    image: nohy6630/yachtdice:latest
    container_name: yachtdice
    ports:
      - 8080:8080
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    hostname: redis