spring:
  profiles:
    include:
      - dev

  jpa:
    defer-datasource-initialization: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true