spring:
  datasource:
    url: jdbc:mysql://yachtdice.cwb8ec1q2sbc.ap-northeast-2.rds.amazonaws.com/yachtdice?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: yachtdice
    driver-class-name: com.mysql.cj.jdbc.Driver